version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=younup.mynextcloud.com
    depends_on:
      - db

  web:
    image: nginx
    networks:
      default:
        aliases:
          - younup.mynextcloud.com
    restart: always
    ports:
      - 443:443
      - 9980:9980
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/cert.pem:/etc/ssl/cert.pem:ro
      - ./web/key.pem:/etc/ssl/key.pem:ro
      - nextcloud:/var/www/html
    depends_on:
      - db
      - app

  online:
    image: collabora/code
    privileged: true
    volumes:
      - ./online/coolwsd.xml:/etc/coolwsd/coolwsd.xml
    environment:
      domain: younup.mynextcloud.com
      username: admin
      password: admin
    restart:
      unless-stopped

volumes:
  db:
  nextcloud:
